/*
  Theme picker. The theme colours and the list of themes live in css/themes.css
  (generated by tools/sync-themes.py). The inline script in each page's <head>
  sets <html data-theme> from localStorage before CSS paints; this code fills the
  picker, saves changes and keeps the browser UI colour (theme-color) in sync.
  "system" follows the device: CSS maps it with prefers-color-scheme.
*/
(function () {
  var KEY = "choconeko-theme";
  var root = document.documentElement;
  var picker = document.querySelector(".theme-picker");
  var select = document.getElementById("theme-select");
  var mq = window.matchMedia ? window.matchMedia("(prefers-color-scheme: dark)") : null;

  function cssVar(name) {
    return getComputedStyle(root).getPropertyValue(name).trim();
  }
  // --theme-list: "id=Name;id=Name;..."
  var themes = cssVar("--theme-list").replace(/^["']|["']$/g, "").split(";")
    .map(function (pair) {
      var i = pair.indexOf("=");
      return { id: pair.slice(0, i).trim(), name: pair.slice(i + 1).replace(/\\(.)/g, "$1").trim() };
    })
    .filter(function (t) { return t.id; });
  var valid = { system: true };
  themes.forEach(function (t) { valid[t.id] = true; });

  function read() {
    var t = null;
    try { t = localStorage.getItem(KEY); } catch (e) { /* storage blocked */ }
    return t && valid[t] ? t : "system";
  }
  function save(choice) {
    try { localStorage.setItem(KEY, choice); } catch (e) { /* storage blocked */ }
  }
  function syncThemeColor() {
    var color = cssVar("--theme-color");
    if (!color) return;
    var metas = document.querySelectorAll('meta[name="theme-color"]');
    for (var i = 0; i < metas.length; i++) {
      if (i === 0) { metas[i].removeAttribute("media"); metas[i].setAttribute("content", color); }
      else metas[i].parentNode.removeChild(metas[i]);
    }
  }
  function apply(choice) {
    root.setAttribute("data-theme", choice);
    if (select && select.value !== choice) select.value = choice;
    syncThemeColor();
  }

  if (select && themes.length) {
    themes.forEach(function (t) {
      var opt = document.createElement("option");
      opt.value = t.id;
      opt.textContent = t.name;
      select.appendChild(opt);
    });
    select.addEventListener("change", function () {
      current = select.value;
      save(current);
      apply(current);
    });
    if (picker) picker.hidden = false;
  }
  // The current choice, kept in memory so it survives even when storage is blocked.
  var current = read();
  apply(current);

  // System mode: CSS already follows the device; keep theme-color in step.
  if (mq) {
    var onSchemeChange = function () { if (current === "system") apply("system"); };
    if (mq.addEventListener) mq.addEventListener("change", onSchemeChange);
    else if (mq.addListener) mq.addListener(onSchemeChange);
  }
  // Keep other open tabs in step.
  window.addEventListener("storage", function (e) {
    if (e.key === KEY) { current = read(); apply(current); }
  });
})();

(function () {
  // Mobile nav toggle
  var toggle = document.querySelector(".nav-toggle");
  var nav = document.getElementById("site-nav");
  if (toggle && nav) {
    var setOpen = function (open) {
      nav.classList.toggle("open", open);
      toggle.setAttribute("aria-expanded", open ? "true" : "false");
    };
    var isOpen = function () { return nav.classList.contains("open"); };

    toggle.addEventListener("click", function () {
      setOpen(!isOpen());
    });
    nav.addEventListener("click", function (e) {
      if (e.target.closest && e.target.closest("a")) setOpen(false);
    });
    // Close on Escape and send focus back to the Menu button
    document.addEventListener("keydown", function (e) {
      if ((e.key === "Escape" || e.key === "Esc") && isOpen()) {
        setOpen(false);
        toggle.focus();
      }
    });
    // Close on a tap/click outside the menu. If focus was inside the menu,
    // return it to the Menu button (unless the tap landed on another control).
    var refocusToggle = false;
    document.addEventListener("pointerdown", function (e) {
      if (!isOpen()) return;
      if (nav.contains(e.target) || toggle.contains(e.target)) return;
      refocusToggle = nav.contains(document.activeElement);
      setOpen(false);
    });
    document.addEventListener("click", function (e) {
      if (!refocusToggle) return;
      refocusToggle = false;
      if (!(e.target.closest && e.target.closest("a, button, input, select, textarea, [tabindex]"))) toggle.focus();
    });
    // Close if keyboard focus leaves the menu (e.g. tabbing past the last link)
    nav.addEventListener("focusout", function (e) {
      if (!isOpen()) return;
      var next = e.relatedTarget;
      if (next && !nav.contains(next) && next !== toggle) setOpen(false);
    });
    // Close when the window grows back to the desktop layout, so the menu isn't
    // unexpectedly open after shrinking again (idea from the portfolio's menu.js).
    var small = window.matchMedia ? window.matchMedia("(max-width: 920px)") : null;
    if (small) {
      var onWidth = function () { if (!small.matches && isOpen()) setOpen(false); };
      if (small.addEventListener) small.addEventListener("change", onWidth);
      else if (small.addListener) small.addListener(onWidth);
    }
  }

  // Footer year
  var year = document.getElementById("year");
  if (year) year.textContent = new Date().getFullYear();

  // Team cards from js/members.js
  var grid = document.getElementById("team-grid");
  var members = window.CHOCONEKO_MEMBERS || [];
  if (!grid || !members.length) return;

  function el(tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text) node.textContent = text;
    return node;
  }
  function link(href, text, external) {
    var a = el("a", "chip-link", text);
    a.href = href;
    if (external) { a.target = "_blank"; a.rel = "noopener"; }
    return a;
  }

  members.forEach(function (m) {
    var card = el("article", "member-card" + (m.lead ? " is-lead" : "") + (m.placeholder ? " is-placeholder" : ""));
    card.id = "member-" + m.id;

    var avatar = el("div", "avatar", m.placeholder ? "?" : m.name.charAt(0));
    avatar.setAttribute("aria-hidden", "true");
    card.appendChild(avatar);
    card.appendChild(el("h3", "", m.name));
    card.appendChild(el("span", "role", m.role));
    if (m.blurb) card.appendChild(el("p", "", m.blurb));

    var links = el("div", "card-links");
    if (m.page) links.appendChild(link(m.page, "Profile"));
    if (m.website) links.appendChild(link(m.website, "Personal site \u2197", true));
    if (!m.page && !m.website) links.appendChild(link("#member-" + m.id, "Link to this card"));
    card.appendChild(links);

    grid.appendChild(card);
  });

  // Highlight + scroll to a linked card (cards are injected after load)
  function focusHash() {
    var prev = grid.querySelector(".is-targeted");
    if (prev) prev.classList.remove("is-targeted");
    if (location.hash.indexOf("#member-") !== 0) return;
    var target = document.getElementById(location.hash.slice(1));
    if (target) { target.classList.add("is-targeted"); target.scrollIntoView(); }
  }
  focusHash();
  window.addEventListener("hashchange", focusHash);
})();
